# Generated by Django 4.0.4 on 2022-06-30 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT: ')),
                ('nombre', models.CharField(max_length=50, verbose_name='NOMBRE: ')),
                ('telefono', models.CharField(max_length=12, verbose_name='TELEFONO: ')),
                ('correo', models.EmailField(max_length=80, verbose_name='CORREO ELECTRONICO: ')),
                ('suscripcion', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
