# Generated by Django 4.0.5 on 2022-06-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='suscripcion',
            field=models.BooleanField(null=True),
        ),
    ]
