# Generated by Django 4.0.5 on 2022-06-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
