# Generated by Django 4.0.4 on 2022-06-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='suscripcion',
            field=models.BooleanField(default=False),
        ),
    ]
